name: {{cookiecutter.project_name}}
channels:
  - defaults
dependencies:
  - python=3.7.*
  - pip:
      - scikit-learn==0.20.*
      - dsflow
      - spacy
      - boto3
      - pandas
      - matplotlib